config/routes.rb
Kaitou::Application.routes.draw do

  resources :b_questions do
    resources :b_answers
  end  

  get "questions/index"
  resources :m_questions do
    resources :m_answers
  end

  root 'questions#index'

end

app/models/b_question.rb
class BQuestion < ActiveRecord::Base
	has_many :b_answers
end

app/controllers/b_questions_controller.rb
class BQuestionsController < ApplicationController
  before_action :set_b_question, only: [:show, :edit, :update, :destroy]
  # GET /b_questions
  # GET /b_questions.json
  def index
    @b_questions = BQuestion.all
  end

  # GET /b_questions/1
  # GET /b_questions/1.json
  def show
    @b_answer = BAnswer.new
  end

  # GET /b_questions/new
  def new
    @b_question = BQuestion.new
  end

  # GET /b_questions/1/edit
  def edit
  end

  # POST /b_questions
  # POST /b_questions.json
  def create
    @b_question = BQuestion.new(b_question_params)

    respond_to do |format|
      if @b_question.save
        format.html { redirect_to @b_question, notice: 'B question was successfully created.' }
        format.json { render action: 'show', status: :created, location: @b_question }
      else
        format.html { render action: 'new' }
        format.json { render json: @b_question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /b_questions/1
  # PATCH/PUT /b_questions/1.json
  def update
    respond_to do |format|
      if @b_question.update(b_question_params)
        format.html { redirect_to @b_question, notice: 'B question was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @b_question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /b_questions/1
  # DELETE /b_questions/1.json
  def destroy
    @b_question.destroy
    respond_to do |format|
      format.html { redirect_to b_questions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_b_question
      @b_question = BQuestion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def b_question_params
      params.require(:b_question).permit(:content)
    end
end

app/helpers/b_questions_helper.rb
module BQuestionsHelper
end

app/views/b_questions/_form.html.haml
= form_for @b_question do |f|
  - if @b_question.errors.any?
    #error_explanation
      %h2= "#{pluralize(@b_question.errors.count, "error")} prohibited this b_question from being saved:"
      %ul
        - @b_question.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :content
    = f.text_area :content
  .actions
    = f.submit 'Save'

app/views/b_questions/edit.html.haml
%h1 Editing b_question

= render 'form'

= link_to 'Show', @b_question
\|
= link_to 'Back', b_questions_path

app/views/b_questions/index.html.haml
%h1 Listing b_questions

%table
  %tr
    %th Content
    %th
    %th
    %th

  - @b_questions.each do |b_question|
    %tr
      %td= b_question.content
      %td= link_to 'Show', b_question
      %td= link_to 'Edit', edit_b_question_path(b_question)
      %td= link_to 'Destroy', b_question, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New B question', new_b_question_path
= link_to '種類選択に戻る', questions_index_path

app/views/b_questions/new.html.haml
%h1 New b_question

= render 'form'

= link_to 'Back', b_questions_path

app/views/b_questions/show.html.haml
%p#notice= notice

%p
  %b Content:
  = @b_question.content

= render 'b_answers/form'
= link_to 'Edit', edit_b_question_path(@b_question)
\|
= link_to 'Back', b_questions_path