config/routes.rb
Kaitou::Application.routes.draw do

  resources :b_questions do
    resources :b_answers
  end  

  get "questions/index"
  resources :m_questions do
    resources :m_answers
  end

  root 'questions#index'

end

app/models/m_question.rb
class MQuestion < ActiveRecord::Base
	has_many :m_answers
end

app/controllers/m_questions_controller.rb
class MQuestionsController < ApplicationController
  before_action :set_m_question, only: [:show, :edit, :update, :destroy]

  # GET /m_questions
  # GET /m_questions.json
  def index
    @m_questions = MQuestion.all
  end

  # GET /m_questions/1
  # GET /m_questions/1.json
  def show
    @m_answer = MAnswer.new


  end

  # GET /m_questions/new
  def new
    @m_question = MQuestion.new
  end

  # GET /m_questions/1/edit
  def edit
  end

  # POST /m_questions
  # POST /m_questions.json
  def create
    @m_question = MQuestion.new(m_question_params)

    respond_to do |format|
      if @m_question.save
        format.html { redirect_to @m_question, notice: 'M question was successfully created.' }
        format.json { render action: 'show', status: :created, location: @m_question }
      else
        format.html { render action: 'new' }
        format.json { render json: @m_question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /m_questions/1
  # PATCH/PUT /m_questions/1.json
  def update
    respond_to do |format|
      if @m_question.update(m_question_params)
        format.html { redirect_to @m_question, notice: 'M question was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @m_question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /m_questions/1
  # DELETE /m_questions/1.json
  def destroy
    @m_question.destroy
    respond_to do |format|
      format.html { redirect_to m_questions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_m_question
      @m_question = MQuestion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def m_question_params
      params.require(:m_question).permit(:content)
    end
end

app/helpers/m_questions_helper.rb
module MQuestionsHelper
end

app/views/m_questions/_form.html.haml
= form_for @m_question do |f|
  - if @m_question.errors.any?
    #error_explanation
      %h2= "#{pluralize(@m_question.errors.count, "error")} prohibited this m_question from being saved:"
      %ul
        - @m_question.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :content
    = f.text_area :content
  .actions
    = f.submit 'Save'

app/views/m_questions/edit.html.haml
%h1 問題を編集する

= render 'form'

= link_to 'Show', @m_question
\|
= link_to 'Back', m_questions_path

app/views/m_questions/index.html.haml
%h1 選択問題一覧

%table
  %tr
    %th 問題内容
    %th
    %th
    %th

  - @m_questions.each do |m_question|
    %tr
      %td= m_question.content
      %td= link_to 'Show', m_question
      %td= link_to 'Edit', edit_m_question_path(m_question)
      %td= link_to 'Destroy', m_question, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to '新しい選択問題を作成する', new_m_question_path
\|
= link_to '種類選択に戻る', questions_index_path

app/views/m_questions/new.html.haml
%h1 新規作成フォーム

= render 'form'

= link_to 'Back', m_questions_path

app/views/m_questions/show.html.haml
%p#notice= notice

%p
  %b Content:
  = @m_question.content

= render 'm_answers/form'

= link_to 'Edit', edit_m_question_path(@m_question)
\|
= link_to 'Back', m_questions_path