config/routes.rb
Kaitou::Application.routes.draw do

  resources :b_questions do
    resources :b_answers
  end  

  get "questions/index"
  resources :m_questions do
    resources :m_answers
  end

  root 'questions#index'

end

app/models/m_answer.rb
class MAnswer < ActiveRecord::Base
	belongs_to :m_question
end

app/controllers/m_answers_controller.rb
class MAnswersController < ApplicationController
  before_action :set_m_answer, only: [:show, :edit, :update, :destroy]
  before_action :set_m_question, except: [:destroy]
  # GET /m_answers
  # GET /m_answers.json
  def index
    @m_answers = MAnswer.all
  end

  # GET /m_answers/1
  # GET /m_answers/1.json
  def show
  end

  # GET /m_answers/new
  def new
    @m_answer = MAnswer.new
  end

  # GET /m_answers/1/edit
  def edit
    @m_answer = @m_question.m_answers.find(params[:id])
  end

  # POST /m_answers
  # POST /m_answers.json
  def create
    @m_answer = @m_question.m_answers.build(m_answer_params)
    respond_to do |format|
      if @m_answer.save
        format.html { redirect_to m_question_m_answer_path(@m_question,@m_answer), notice: 'M answer was successfully created.' }
        format.json { render action: 'show', status: :created, location: @m_answer }
      else
        format.html { render action: 'new' }
        format.json { render json: @m_answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /m_answers/1
  # PATCH/PUT /m_answers/1.json
  def update
    @m_answer = @m_question.m_answers.build(m_answer_params)
    respond_to do |format|
      if @m_answer.update(m_answer_params)
        format.html { redirect_to m_question_m_answer_path(@m_question,@m_answer), notice: 'M answer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @m_answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /m_answers/1
  # DELETE /m_answers/1.json
  def destroy

    @m_answer.destroy
    respond_to do |format|
      format.html { redirect_to m_question_m_answers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_m_answer
      @m_answer = MAnswer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def m_answer_params
      params.require(:m_answer).permit(:check, :answer)
    end

    def set_m_question
      @m_question = MQuestion.find(params[:m_question_id])
    end
end

app/helpers/m_answers_helper.rb
module MAnswersHelper
end

app/views/m_answers/_form.html.haml
= form_for [@m_question, @m_answer] do |f|
  - if @m_answer.errors.any?
    #error_explanation
      %h2= "#{pluralize(@m_answer.errors.count, "error")} prohibited this m_answer from being saved:"
      %ul
        - @m_answer.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :check
    = f.check_box :check
  .field
    = f.label :answer
    = f.text_field :answer
  .actions
    = f.submit 'Save'

app/views/m_answers/edit.html.haml
%h1 Editing m_answer

= render 'form'

= link_to 'Show', m_question_m_answer_path(@m_question,@m_answer)
\|
= link_to 'Back', m_question_m_answers_path

app/views/m_answers/index.html.haml
%h1 Listing m_answers

%table
  %tr
    %th Check
    %th Answer
    %th
    %th
    %th

  - @m_answers.each do |m_answer|
    %tr
      %td= m_answer.check
      %td= m_answer.answer
      %td= link_to 'Show', m_question_m_answer_path(@m_question, m_answer)
      %td= link_to 'Edit', edit_m_question_m_answer_path(@m_question, m_answer)
      %td= link_to 'Destroy', m_question_m_answer_path(@m_question, m_answer), :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New M answer', new_m_question_m_answer_path

app/views/m_answers/new.html.haml
%h1 New m_answer

= render 'form'

= link_to 'Back', m_question_m_answers_path

app/views/m_answers/show.html.haml
%p#notice= notice

%p
  %b Check:
  = @m_answer.check
%p
  %b Answer:
  = @m_answer.answer

= link_to 'Edit', edit_m_question_m_answer_path(@m_question,@m_answer)
\|
= link_to 'Back', m_question_m_answers_path