config/routes.rb
Kaitou::Application.routes.draw do

  resources :b_questions do
    resources :b_answers
  end  

  get "questions/index"
  resources :m_questions do
    resources :m_answers
  end

  root 'questions#index'

end

app/models/b_answer.rb
class BAnswer < ActiveRecord::Base
	belongs_to :b_question
end

app/controllers/b_answers_controller.rb
class BAnswersController < ApplicationController
  before_action :set_b_answer, only: [:show, :edit, :update, :destroy]
  before_action :set_b_question, except: [:destroy]
  # GET /b_answers
  # GET /b_answers.json
  def index
    @b_answers = BAnswer.all
  end

  # GET /b_answers/1
  # GET /b_answers/1.json
  def show
  end

  # GET /b_answers/new
  def new
    @b_answer = BAnswer.new
  end

  # GET /b_answers/1/edit
  def edit
    @b_answer = @b_question.b_answers.find(params[:id])
  end

  # POST /b_answers
  # POST /b_answers.json
  def create
    @b_answer = @b_question.b_answers.build(b_answer_params)

    respond_to do |format|
      if @b_answer.save
        format.html { redirect_to b_question_b_answer_path(@b_question,@b_answer), notice: 'B answer was successfully created.' }
        format.json { render action: 'show', status: :created, location: @b_answer }
      else
        format.html { render action: 'new' }
        format.json { render json: @b_answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /b_answers/1
  # PATCH/PUT /b_answers/1.json
  def update
    @b_answer = @b_question.b_answers.build(m_answer_params)
    respond_to do |format|
      if @b_answer.update(b_answer_params)
        format.html { redirect_to b_question_b_answer_path(@b_question,@b_answer), notice: 'B answer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @b_answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /b_answers/1
  # DELETE /b_answers/1.json
  def destroy
    @b_answer.destroy
    respond_to do |format|
      format.html { redirect_to b_question_b_answers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_b_answer
      @b_answer = BAnswer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def b_answer_params
      params.require(:b_answer).permit(:answer)
    end

    def set_b_question
      @b_question = BQuestion.find(params[:b_question_id])
    end
end

app/helpers/b_answers_helper.rb
module BAnswersHelper
end

app/views/b_answers/_form.html.haml
= form_for [@b_question, @b_answer] do |f|
  - if @b_answer.errors.any?
    #error_explanation
      %h2= "#{pluralize(@b_answer.errors.count, "error")} prohibited this b_answer from being saved:"
      %ul
        - @b_answer.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :answer
    = f.text_field :answer
  .actions
    = f.submit 'Save'

app/views/b_answers/edit.html.haml
%h1 Editing b_answer

= render 'form'

= link_to 'Show', b_question_b_answer_path(@b_question,@b_answer)
\|
= link_to 'Back', b_question_b_answers_path

app/views/b_answers/index.html.haml
%h1 Listing b_answers

%table
  %tr
    %th Answer
    %th
    %th
    %th

  - @b_answers.each do |b_answer|
    %tr
      %td= b_answer.answer
      %td= link_to 'Show', b_question_b_answer_path(@b_question,b_answer)
      %td= link_to 'Edit', edit_b_question_b_answer_path(@b_question, b_answer)
      %td= link_to 'Destroy', b_question_b_answer_path(@b_question, b_answer), :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New B answer', new_b_question_b_answer_path

app/views/b_answers/new.html.haml
%h1 New b_answer

= render 'form'

= link_to 'Back', b_question_b_answers_path

app/views/b_answers/show.html.haml
%p#notice= notice

%p
  %b Answer:
  = @b_answer.answer

= link_to 'Edit', edit_b_question_b_answer_path(@b_question,@b_answer)
\|
= link_to 'Back', b_question_b_answers_path